import image1 from '@/public/images/cleaning-products/image1.jpeg';
import image2 from '@/public/images/cleaning-products/image2.jpeg';
import image3 from '@/public/images/cleaning-products/image3.jpeg';
import image4 from '@/public/images/cleaning-products/image4.jpeg';
import image5 from '@/public/images/cleaning-products/image5.jpeg';
import image6 from '@/public/images/cleaning-products/image6.jpeg';

export const PAGE_SECTION_ONE = [
  {
    header: 'Stain Extinguisher™ & World Famous™ Professional Strength Spot Remover',
    paragraphs: [
      'Stains are always a problem when it comes to fabrics, and maintaining a beautiful appearance for your household materials is not always easy. If your carpet or upholstered furniture is suffering from unwanted marks that won’t budge, then you need the assistance of Chem-Dry’s professional products.',
      'Our products have been tried and tested and are trusted by professionals the world over. They are effective at removing stains and dirt from colourfast upholstery, carpets and car interiors. Each of our products is used together with our powerful Chem-Dry carbonating process making for the most efficient cleaning method available.',
      'World Famous™ Professional Strength Spot Remover is very effective at dealing with oil-based stains. As an added bonus, it is also very effective when used as a pre-wash spotting agent for difficult laundry stains.',
      'All of our products are guaranteed to do their job and will leave no residues on your fabrics.',
    ],
    image: image1,
    small: true,
  },
];

export const PAGE_SECTION_TWO = [
  {
    header: 'Grease & Oil Remover',
    paragraphs: [
      'Stubborn stains such as tar, lipstick, oil and adhesives can be a real problem to remove and can usually only be dealt with by harsh agents containing solvents.',
      'Whilst these products might be effective, they can be a hazard to health as they contain solvent-based ingredients. Here at Chem-Dry Milton Keynes we like to recommend our Grease and Oil Remover to deal with these stains. Many of our products are entirely natural and rely on grains, herbs and fruit-based cleaners held in a water base.',
      'Grease and Oil Remover is 100% evaporative and residue free.',
    ],
    image: image2,
    small: true,
    grey: true,
  },
];

export const PAGE_SECTION_THREE = [
  {
    header: 'Carpet Deodorisers',
    paragraphs: [
      'We offer carpet deodorisers in a wide range of scents, including Apple Cinnamon, and Lemon Grove. Our effective products work hard to counteract household smells such as pet odours and those generated by smoke and cooking.',
      'Special polymers are present in each fragrance and these attach to the fibres of your carpet. When you walk on your carpet these polymers react and release bursts of fragrance around your home.',
      'Each of our Chem-Dry Carpet Deodorisers contain concentrated fragrances which means that one product can last up to five times longer than the equivalent powder product. Due to our products being in liquid form, no dusty powders are released that could attract dirt or irritate anybody in the vicinity.',
    ],
    image: image3,
    small: true,
  },
];

export const PAGE_SECTION_FOUR = [
  {
    header: 'Dust Mite Anti-Allergen Spray',
    paragraphs: [
      'Dust mites are a real problem in the home. The most effective way of dealing with these pests and stopping allergies is to attack the source. Dust mites can be present anywhere where there is dust so that literally means anywhere and everywhere in the home. Our Dust Mite Anti-Allergen Spray has been tested in laboratories and tests show this product is extremely effective at removing the allergens that are produced by dust mites.',
      'The Chem-Dry Dust Mite Anti-Allergen formula is completely natural and contains no harsh or harmful chemicals. This product is suitable for bedding, mattresses and any other home furnishings that are effective. Our products are completely safe for use around the home.',
    ],
    image: image4,
    small: true,
    grey: true,
  },
];

export const PAGE_SECTION_FIVE = [
  {
    header: 'Fabric Stain Protector',
    paragraphs: [
      'Our exclusive stain protector has been designed specifically to protect the carpets and upholstery around your home.',
      'Once applied to your fabric, carpets, furniture or upholstery, the solution will form an invisible barrier which stops dirt becoming embedded in the fibres. This coating will also act as a water repellent, so any stains are then held on the surface, and you can simply wipe away spillages with a cloth',
      'We only supply our customers with the most advanced and effective stain protection products that, importantly, don’t damage your materials.',
    ],
    image: image5,
    small: true,
  },
];

export const PAGE_SECTION_SIX = [
  {
    header: 'Carpet Rake',
    paragraphs: [
      'Our Carpet Rake is very effective at keeping the spring in your carpets as well as having many other advantages. If used regularly, the Carpet Rake will reduce the pile that can become matted in doorways and foot-wells.',
      'When used before you vacuum, the Carpet Rake will loosen dirt and grit making vacuuming easier and more effective.',
      'The Carpet Rake helps you to achieve brighter and cleaner carpets in between professional Chem-Dry cleans.',
    ],
    image: image6,
    small: true,
    grey: true,
  },
];

export const CONTENT_BAR = {
  title: 'Our Cleaning Products',
  paragraph:
    'Our products let you achieve a cleaner & healthier home or business. All of our products are suitable for use in-between our professional Chem-Dry cleans',
};
