import StyledComponentsRegistry from './lib/registry';
import { Roboto_Condensed } from 'next/font/google';

import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const robotoCondensed = Roboto_Condensed({
  subset: ['latin'],
  weight: ['400', '700'],
  preload: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body style={{ margin: 0 }} className={robotoCondensed.className}>
        <Header />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        <Footer />
      </body>
    </html>
  );
}
