export const HOMEPAGE = `
  {
  homepage(id: "1WdHdBja7O8iulUQTIpsMJ") {
    heroSection{
      carouselCollection{
        items{
          image{
          title
          description
          url
          width
          height
        }
        subtitle
        title
        ctaCopy
        ctaUrl
        }
      }
      borderColour
    }
    topSection{
      carousel{
        carouselSlideCollection{
          items{
            url
            title
          }
        }
      }
      sectionTitle
      content{
        json
      }
      icon{
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
      backgroundColour
    }
    middleSection{
      sectionTitle
      content{
        json
      }
      carousel{
        carouselSlideCollection{
          items{
            url
            title
          }
        }
      }
      icon{
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
      backgroundColour
    }
    fullWidthBar{
      category
      title
      image{
        title
        description
        width
        height
        url
      }
      url
    }
    bottomSection{
      sectionTitle
      content{
        json
      }
      carousel{
        carouselSlideCollection{
          items{
            url
            title
          }
        }
      }
      icon{
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
      backgroundColour
    }
  }
}
`;

export const SERVICES = `
  {
  pageCollection(where: { slug_exists: true }, preview:false){
    items{
      slug
      title
      thumbnail{
        url
        width
        height
        title
      }
    }
  }
}
`;

export const TOPBAR = `
  {
  homepage(id: "1WdHdBja7O8iulUQTIpsMJ"){
    topSubHeader{
      text
      backgroundColour
    }
  }
}
`;

export const SERVICE = `
  slug
  title
  heroSection{
    carouselCollection{
      items{
        image{
        title
        description
        url
        width
        height
      }
      subtitle
      title
      ctaCopy
      ctaUrl
      }
    }
    borderColour
  }
  topSection {
      sectionTitle
      content {
        json
      }
      carousel{
        carouselSlideCollection{
          items{
            url
            title
          }
        }
      }
      icon {
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
    }
    middleSection {
      sectionTitle
      content {
        json
      }
      carousel{
        carouselSlideCollection{
          items{
            url
            title
          }
        }
      }
      icon {
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
    }
    bottomSection {
      sectionTitle
      content {
        json
      }
      carousel{
        carouselSlideCollection{
          items{
            url
            title
          }
        }
      }
      icon {
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
    }
    fullWidthBar{
      category
      title
      url
      image {
        title
        description
        width
        height
        url
      }
    }
`;
