export const HOMEPAGE = `
  {
  homepage(id: "1WdHdBja7O8iulUQTIpsMJ") {
    topSection{
      sectionTitle
      content{
        json
      }
      icon{
        title
        description
        width
        height
        url
      }
      image{
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
      backgroundColour
    }
    servicesCollection{
      items{
        title
        subtitle
        image{
          title
          description
          url
          width
          height
        }
        description{
          json
        }
        service{
          title
          slug
        }
      }
    }
    middleSection{
      sectionTitle
      content{
        json
      }
      icon{
        title
        description
        width
        height
        url
      }
      image{
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
      backgroundColour
    }
    fullWidthBar{
      category
      title
      image{
        title
        description
        width
        height
        url
      }
      url
    }
    bottomSection{
      sectionTitle
      content{
        json
      }
      icon{
        title
        description
        width
        height
        url
      }
      image{
        title
        description
        width
        height
        url
      }
      imagePosition
      addReviewCards
      backgroundColour
    }
  }
}
`;

export const SERVICES = `
  {
  pageCollection(where: { slug_exists: true }, preview:false){
    items{
      slug
      title
      thumbnail{
        url
        width
        height
        title
      }
    }
  }
}
`;

export const SERVICE = `
    slug
    title
    topSection {
        sectionTitle
        content {
          json
        }
        icon {
          title
          description
          width
          height
          url
        }
        image {
          title
          description
          width
          height
          url
        }
        imagePosition
        addReviewCards
      }
      middleSection {
        sectionTitle
        content {
          json
        }
        icon {
          title
          description
          width
          height
          url
        }
        image {
          title
          description
          width
          height
          url
        }
        imagePosition
        addReviewCards
      }
      bottomSection {
        sectionTitle
        content {
          json
        }
        icon {
          title
          description
          width
          height
          url
        }
        image {
          title
          description
          width
          height
          url
        }
        imagePosition
        addReviewCards
      }
      fullWidthBar{
          category
          title
          url
          image{
            title
            description
            width
            height
            url
          }
        }
`;
